[default]

[default.db]
uri = ""
connect_args = {check_same_thread=false}
echo = false

[default.security]
# Set secret key in .secrets.toml
# SECRET_KEY = ""
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 120
REFRESH_TOKEN_EXPIRE_MINUTES = 600

[default.version_api]
VERSION_API_STR = "/api/v1"